<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A new comment was left for project "{projectTitle}".' => 'Un nouveau commentaire a été déposé pour le projet "{projectTitle}".',
    'Account activation' => 'Activation du compte',
    'Activate account' => 'Activer le compte',
    'Administrator assignment' => 'Assignation d\'un administrateur',
    'Administrator discharge' => 'Révocation d\'un administrateur',
    'Best Regards' => 'Cordialement',
    'Click on the button below for detail view and other options:' => 'Cliquez le bouton ci-dessous pour une vue détaillée et d\'autres options:',
    'Click on the button below to activate your account:' => 'Cliquez le bouton ci-dessous pour activer votre compte:',
    'Click on the button below to continue:' => 'Cliquez le bouton ci-dessous pour continuer:',
    'Click on the button below to explore the project:' => 'Cliquez le bouton ci-dessous pour explorer le projet:',
    'Click on the button below to reset it and set a new one:' => 'Cliquez le bouton ci-dessous pour le réinitialiser et en choisir un nouveau:',
    'Detail view' => 'Vue détaillée',
    'Explore project' => 'Explorer le projet',
    'From' => 'De',
    'Hello' => 'Bonjour',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Si vous avez besoin d\'assistance, n\'hésitez pas à nous contacter sur {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Si vous pensez que ce message a été envoyé par erreur ou que vous avez besoin d\'aide, n\'hésitez pas à nous contacter sur {supportEmail}.',
    'Message' => 'Message',
    'New comment' => 'Nouveau commentaire',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'PS: Si vous ne souhaitez pas recevoir de notifications pour les commentaires, vous pouvez mettre à jour vos préférences dans les réglages de votre compte Presentator.',
    'Password reset request' => 'Demande de réinitialisation de mot de passe',
    'Presentator Team' => 'L\'équipe Presentator',
    'Registered with Facebook' => 'Enregistré avec Facebook',
    'Reset password' => 'Réinitialiser le mot de passe',
    'Screen' => 'Ecran',
    'Thank you for registering to {appLink}.' => 'Merci de votre souscription à {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'Pour vous permettre de vous connecter sans l\'authentification Facebook, nous avons défini un mot de passe aléatoire pour votre compte :',
    'View project' => 'Voir le projet',
    'We\'ve received a request to reset your account password.' => 'Nous avons reçu une demande de réinitialisation de votre mot de passe:',
    'You are assigned as admin to project "{projectTitle}".' => 'Vous êtes assignés en tant qu\'administrateur du projet "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Vous êtes invités à revoir le design de "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Vous n\'êtes désormais plus administrateur du projet "{projectTitle}".',
    'You have successfully registered via Facebook.' => 'Vous vous êtes bien authentifiés via Facebook.',
    '{projectTitle} preview' => 'Aperçu de {projectTitle}',
];
