<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm email address change' => '',
    'Email change request' => '',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => '',
    'You have been mentioned in a comment' => '',
    'You have been mentioned in a comment for project "{projectTitle}".' => '',
    'A new comment was left for project "{projectTitle}".' => 'Um novo comentário para o projeto "{projectTitle}" foi escrito.',
    'Account activation' => 'Ativação de conta',
    'Activate account' => 'Ativar conta',
    'Administrator assignment' => 'Atribuição de administrador',
    'Administrator discharge' => 'Remoção de administrador',
    'Best Regards' => 'Atenciosamente',
    'Click on the button below for detail view and other options:' => 'Clique no botão abaixo para visualização detalhada e outras opções:',
    'Click on the button below to activate your account:' => 'Clique no botão abaixo para ativar a sua conta:',
    'Click on the button below to continue:' => 'Clique no botão abaixo para avançar:',
    'Click on the button below to explore the project:' => 'Clique no botão abaixo para explorar o projeto:',
    'Click on the button below to reset it and set a new one:' => 'Clique no botão abaixo para redefinir:',
    'Detail view' => 'Visualização detalhada',
    'Explore project' => 'Explorar projeto',
    'From' => 'De',
    'Hello' => 'Olá',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Se precisar de mais ajuda, não hesite em nos contato no email {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Se esta mensagem é um erro ou se precisar de mais ajuda, não hesite em nos contatar no email {supportEmail}.',
    'Message' => 'Mensagem',
    'New comment' => 'Novo comentário',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S. Se não quiser receber mais notificações de comentário, atualize suas preferências nas configurações de conta do Presentator',
    'Password reset request' => 'Pedido de redefinição de senha enviado',
    'Presentator Team' => 'Time Presentator',
    'Registered with Facebook' => 'Registrado com Facebook',
    'Reset password' => 'Redefinir senha',
    'Screen' => 'Tela',
    'Thank you for registering to {appLink}.' => 'Obrigado por se registar para {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'Para poder efetuar login sem o Facebook, definimos uma senha aleatória para sua conta:',
    'View project' => 'Ver projeto',
    'We\'ve received a request to reset your account password.' => 'Recebemos um pedido para redefinir sua senha',
    'You are assigned as admin to project "{projectTitle}".' => 'Você foi escolhido como administrador do projeto "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Você foi convidado para revisar o design de "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Você não é mais um administrador do projeto "{projectTitle}".',
    'You have successfully registered via Facebook.' => 'Você se registrou com sucesso usando Facebook.',
    '{projectTitle} preview' => 'visualização de {projectTitle}',
];
