<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator.io account settings page.' => '',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => '@@P.D. Si no quieres recibir más notificaciones de comentarios, puedes actualizar tus preferencias desde el apartado de tu perfil en Presentator.@@',
    'A new comment was left for project "{projectTitle}".' => 'Se ha añadido un nuevo comentario en el proyecto "{projectTitle}".',
    'Account activation' => 'Activación de la cuenta',
    'Activate account' => 'Activar cuenta',
    'Administrator assignment' => 'Tarea de administrador',
    'Administrator discharge' => 'Administrator discharge',
    'Best Regards' => 'Cordial saludo',
    'Click on the button below for detail view and other options:' => 'Haz clic en el botón abajo para ver los detalles y otras opciones:',
    'Click on the button below to activate your account:' => 'Haz clic en el botón abajo para activar tu cuenta:',
    'Click on the button below to continue:' => 'Haz clic en el botón abajo para continuar:',
    'Click on the button below to explore the project:' => 'Haz clic en el botón abajo para ver el proyecto:',
    'Click on the button below to reset it and set a new one:' => 'Haz clic en el botón de abajo para restablecerla y crear una nueva:',
    'Detail view' => 'Vista detallada',
    'Explore project' => 'Explorar proyecto',
    'From' => 'De',
    'Hello' => '¡Hola!',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Si necesitas más ayuda, no dudes en contactar con nosotros en {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Si piensas que este mensaje ha sido un error o necesitas más ayuda, no dudes de contactar con nosotros en {supportEmail}.',
    'Message' => 'Mensaje',
    'New comment' => 'Nuevo comentario',
    'Password reset request' => 'Solicitud de cambio de contraseña',
    'Presentator Team' => 'Equipo de Presentator',
    'Registered with Facebook' => 'Registrado con Facebook',
    'Reset password' => 'Cambiar contraseña',
    'Screen' => 'Pantalla',
    'Thank you for registering to {appLink}.' => 'Gracias por registrarte en {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'Para poder acceder sin la necesidad de autenticación mediante Facebook, te hemos generado una contraseña aleatoria para tu cuenta:',
    'View project' => 'Ver proyecto',
    'We\'ve received a request to reset your account password.' => 'Hemos recibido una petición para restablecer la contraseña de tu cuenta.',
    'You are assigned as admin to project "{projectTitle}".' => 'Has sido añadido como administrador del proyecto "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Has sido invitado a revisar el diseño de "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Ya no eres administrador del proyecto "{projectTitle}".',
    'You have successfully registered via Facebook.' => 'Te has registrado correctamente mediante Facebook.',
    '{projectTitle} preview' => '{projectTitle} previsualización',
];
