<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'A new comment was left for project "{projectTitle}".' => 'Dodano nowy komentarz do projektu "{projectTitle}".',
    'Activate account' => 'Aktywuj konto',
    'Best Regards' => 'Pozdrawiamy',
    'Click on the button below for detail view and other options:' => 'Kliknij przycisk poniżej, aby zobaczyć widok szczegółowy i pozostałe opcje:',
    'Click on the button below to activate your account:' => 'Kliknij przycisk poniżej, aby aktywować swoje konto:',
    'Click on the button below to continue:' => 'Kliknij przycisk poniżej, aby kontynuować:',
    'Click on the button below to explore the project:' => 'Kliknij przycisk poniżej, aby zapoznać się z projektem:',
    'Click on the button below to reset it and set a new one:' => 'Kliknij przycisk poniżej, aby je zresetować i ustawić nowe:',
    'Detail view' => 'Widok szczegółowy',
    'Explore project' => 'Zapoznaj się z projektem',
    'From' => 'Od',
    'Hello' => 'Witaj',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Jeśli potrzebujesz dalszej pomocy, skontaktuj się z nami pod adresem {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Jeśli uważasz, że ta wiadomość została wysłana do Ciebie przez pomyłkę lub potrzebujesz dalszej pomocy, skontaktuj się z nami pod adresem {supportEmail}.',
    'Message' => 'Wiadomość',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S. Jeśli nie chcesz otrzymywać więcej powiadomień o komentarzach, możesz wyłączyć je w ustawieniach konta na stronie Presentator.',
    'Presentator Team' => 'Zespół Presentator',
    'Reset password' => 'Zresetuj hasło',
    'Screen' => 'Ekran',
    'Thank you for registering to {appLink}.' => 'Dziękujemy za rejestrację w {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'Aby umożliwić logowanie z pominięciem uwierzytelniania za pomocą serwisu Facebook, dodaliśmy losowe hasło do Twojego konta:',
    'View project' => 'Zobacz projekt',
    'We\'ve received a request to reset your account password.' => 'Otrzymaliśmy prośbę o zresetowanie hasła do Twojego konta.',
    'You are assigned as admin to project "{projectTitle}".' => 'Zostałeś przydzielony jako administrator w projekcie "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Zostałeś poproszony o recenzję projektu "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Nie jesteś już administratorem projektu "{projectTitle}".',
    'You have successfully registered via Facebook.' => 'Zarejestrowałeś się pomyślnie za pomocą serwisu Facebook.',
);
