<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Alinhamento',
    'Allow comments' => 'Habilite comentários',
    'Allow guideline' => 'Habilite guias',
    'Archived' => 'Arquivado',
    'Avatar' => 'Avatar',
    'Background' => 'Fundo',
    'Client' => 'Cliente',
    'Code' => 'Código',
    'Delete avatar' => 'Apagar avatar',
    'Description' => 'Descrição',
    'Email' => 'Email',
    'Email address domain is not allowed.' => 'Domínio de endereço de email não permitido.',
    'Failed to authorize.' => 'Falha ao autorizar.',
    'File' => 'Arquivo',
    'First name' => 'Primeiro nome',
    'Fixed footer' => 'Rodapé fixo',
    'Fixed header' => 'Cabeçalho fixo',
    'From' => 'De',
    'Height' => 'Altura',
    'Horizontal position' => 'Posiç',
    'Invalid HEX color code.' => 'Código HEX inválido.',
    'Invalid formatted value.' => 'Valor formatado inválido.',
    'Invalid guideline section ID.' => 'ID de seção de guia inválido.',
    'Invalid hotspot template ID.' => 'ID de template de hostspot inválido.',
    'Invalid login credentials.' => 'Credenciais de login inválidas.',
    'Invalid or expired token.' => 'Token inválido ou expirado.',
    'Invalid password.' => 'Senha inválida.',
    'Invalid primary comment ID.' => 'ID de comentário primário inválido.',
    'Invalid project ID.' => 'ID de projeto inválido.',
    'Invalid prototype ID.' => 'ID de protótipo invalido.',
    'Invalid screen ID.' => 'ID de tela inválido.',
    'Last name' => 'Sobrenome',
    'Left' => 'Esquerda',
    'Message' => 'Mensagem',
    'New password' => 'Nova senha',
    'New password confirm' => 'Confirma nova senha',
    'Notify on each comment' => 'Notificar em cada comentário',
    'Notify on mention' => 'Notifique se mencionado',
    'Old password' => 'Senha antiga',
    'Oops, an error occurred while processing your request.' => 'Opa, ocorreu um erro ao processar seu pedido.',
    'Order' => 'Ordenar',
    'Overlay position' => 'Posição sobreposição',
    'Password' => 'Senha',
    'Password confirm' => 'Confirmar senha',
    'Passwords don\'t match.' => 'Senha não combinam.',
    'Prototypes' => 'Protótipos',
    'Reply to' => 'Responda para',
    'Scale factor' => 'Fator de escala',
    'Screen' => 'Tela',
    'Status' => 'Status',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'O que você procura não existe ou está temporariamente indisponível.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'Há um administrador de projeto com tal endereço de email. Administradores de projeto devem usar a área de administração para comentar.',
    'Title' => 'Título',
    'Token' => 'Token',
    'Top' => 'Topo',
    'Transition' => 'Transição',
    'Type' => 'Tipo',
    'Url' => 'URL',
    'User with such email address already exist.' => 'Usuário com este endereço de email já existe.',
    'Vertical position' => 'Posição vertical',
    'Width' => 'Largura',
    'You are not allowed to perform this request.' => 'Você não está permitido executar essa requisição.',
    'You cannot unlink the only user of the project.' => 'Você não pode desconectar o único usuário do projeto.',
);
