<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Ativação de conta',
    'Activate account' => 'Ativar conta',
    'Administrator assignment' => 'Atribuição de administrador',
    'Administrator discharge' => 'Remoção de administrador',
    'Best Regards' => 'Atenciosamente',
    'Click on the button below for detail view and other options:' => 'Clique no botão abaixo para visualização detalhada e outras opções:',
    'Click on the button below to activate your account:' => 'Clique no botão abaixo para ativar a sua conta:',
    'Click on the button below to explore the project:' => 'Clique no botão abaixo para explorar o projeto:',
    'Confirm email address change' => 'Confirme mudança de endereço de email',
    'Detail view' => 'Visualização detalhada',
    'Email change confirmation' => 'Confirmação de alteração de email',
    'Explore project' => 'Explorar projeto',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Por motivos de segurança, incentivamos você a alterar a senha gerada assim que possível.',
    'Hello' => 'Olá',
    'Password reset request' => 'Pedido de redefinição de senha enviado',
    'Presentator Team' => 'Time Presentator',
    'Reset password' => 'Redefinir senha',
    'Successfully authenticated' => 'Autenticado com sucesso',
    'Thank you for your registration at Presentator.' => 'Obrigado pelo seu cadastro no Presentator.',
    'To update your password, click the button below:' => 'Para atualizar a sua senha clique no botão abaixo:',
    'Unread comment' => 'Comentário não lido',
    'View design' => 'Visualizar o design',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Para poder efetuar login sem o 3rd party, definimos uma senha aleatória para sua conta.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Recebemos um pedido para alterar o email da sua conta Presentator de {oldEmail} para {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Recebemos um pedido para redefinir sua senha.',
    'You are invited to review the design for project "{projectTitle}".' => 'Você está convidado para revisar o design do projeto "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'Você foi assinalado como administrador do projeto "{projectTitle}".',
    'You have been mentioned in a comment' => 'Você foi mencionado em um comentário',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Você foi mencionado em um comentário para a tela  "{screenTitle}" do projeto "{projectTitle}":',
    'You have been removed from project "{projectTitle}".' => 'Você foi removido do projeto "{projectTitle}".',
    'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Você tem comentários não lidos para a tela "{screenTitle}" do projeto "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Sua conta Presentator foi criado com sucesso.',
    '{projectTitle} preview' => 'visualização de {projectTitle}',
);
