<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Alignement',
    'Allow comments' => 'Autoriser les commentaires',
    'Allow guideline' => 'Autoriser la charte graphique',
    'Archived' => 'Archivé',
    'Avatar' => 'Avatar',
    'Background' => 'Arrière plan',
    'Client' => 'Client',
    'Code' => 'Code',
    'Delete avatar' => 'Supprimer l\'avatar',
    'Description' => 'Description',
    'Email' => 'Email',
    'Email address domain is not allowed.' => 'Le domaine de l\'adresse email n\'est pas autorisé.',
    'Failed to authorize.' => 'Echec lors de l\'autorisation.',
    'File' => 'Fichier',
    'First name' => 'Prénom',
    'Fixed footer' => 'Pied de page fixe',
    'Fixed header' => 'Haut de page fixe',
    'From' => 'De',
    'Height' => 'Hauteur',
    'Horizontal position' => 'Position horizontale',
    'Invalid HEX color code.' => 'Code couleur hexadécimal non valide.',
    'Invalid formatted value.' => 'Format invalide.',
    'Invalid guideline section ID.' => 'ID de charte graphique invalide.',
    'Invalid hotspot template ID.' => 'ID de gabarit invalide',
    'Invalid login credentials.' => 'Votre identifiant ou votre mot de passe est incorrect.',
    'Invalid or expired token.' => 'Code d\'autorisation invalide ou expiré.',
    'Invalid password.' => 'Mot de passe non valide.',
    'Invalid primary comment ID.' => 'ID de commentaire non valide.',
    'Invalid project ID.' => 'ID de projet non valide.',
    'Invalid prototype ID.' => 'ID de prototype non valide.',
    'Invalid screen ID.' => 'ID d\'écran non valide.',
    'Last name' => 'Nom',
    'Left' => 'Gauche',
    'Message' => 'Message',
    'New password' => 'Nouveau mot de passe',
    'New password confirm' => 'Confirmation du nouveau mot de passe',
    'Notify on each comment' => 'Notifier à chaque commentaire',
    'Notify on mention' => 'Notifier lors de mention',
    'Old password' => 'Ancien mot de passe',
    'Oops, an error occurred while processing your request.' => 'Oups, une erreur est survenue durant le traitement de votre requête.',
    'Order' => 'Ordre',
    'Overlay position' => 'Position de l\'overlay',
    'Password' => 'Mot de passe',
    'Password confirm' => 'Confirmation du mot de passe',
    'Passwords don\'t match.' => 'Les mots de passe ne correspondent pas.',
    'Prototypes' => 'Prototypes',
    'Reply to' => 'Répondre à',
    'Scale factor' => 'Facteur d\'agrandissement',
    'Screen' => 'Ecran',
    'Status' => 'Statut',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'Ce que vous recherchez n\'existe pas ou est temporairement indisponible.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'Il existe un administrateur avec cette adresse email. Les administrateurs de projets devraient utiliser la zone d\'administration pour commenter.',
    'Title' => 'Titre',
    'Token' => 'Jeton',
    'Top' => 'Haut',
    'Transition' => 'Transition',
    'Type' => 'Type',
    'Url' => 'Url',
    'User with such email address already exist.' => 'Cette adresse email est déjà utilisée par un autre utilisateur.',
    'Vertical position' => 'Position verticale',
    'Width' => 'Largeur',
    'You are not allowed to perform this request.' => 'Vous n\'êtes pas autorisé à procéder à cette requête.',
    'You cannot unlink the only user of the project.' => 'Vous ne pouvez pas supprimer le seul utilisateur du projet.',
);
