<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Activation du compte',
    'Activate account' => 'Activer le compte',
    'Administrator assignment' => 'Assignation d\'un administrateur',
    'Administrator discharge' => 'Révocation d\'un administrateur',
    'Best Regards' => 'Cordialement',
    'Click on the button below for detail view and other options:' => 'Cliquez le bouton ci-dessous pour une vue détaillée et d\'autres options :',
    'Click on the button below to activate your account:' => 'Cliquez le bouton ci-dessous pour activer votre compte :',
    'Click on the button below to explore the project:' => 'Cliquez le bouton ci-dessous pour explorer le projet :',
    'Confirm email address change' => 'Confirmer le changement d\'e-mail',
    'Detail view' => 'Vue détaillée',
    'Email change confirmation' => 'Confirmation de changement d\'e-mail',
    'Explore project' => 'Explorer le projet',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Pour des raisons de sécurité, nous vous encourageons à modifier le mot de passe généré dès que possible.',
    'Hello' => 'Bonjour',
    'Password reset request' => 'Demande de réinitialisation de mot de passe',
    'Presentator Team' => 'L\'équipe Presentator',
    'Reset password' => 'Réinitialiser le mot de passe',
    'Successfully authenticated' => 'Authentifié avec succès',
    'Thank you for your registration at Presentator.' => 'Merci pour votre inscription à Presentator.',
    'To update your password, click the button below:' => 'Pour changer votre mot de passe, cliquez sur le bouton ci-dessous :',
    'Unread comment' => 'Commentaire non lu',
    'View design' => 'Voir le design',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Pour vous permettre de vous connecter sans l\'authentification 3ème partie, nous avons défini un mot de passe aléatoire pour votre compte.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Nous avons reçu une demande de changement d\'adresse e-mail de {oldEmail} à {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Nous avons reçu une demande de réinitialisation de votre mot de passe:',
    'You are invited to review the design for project "{projectTitle}".' => 'Vous êtes invités à revoir le design de "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'Vous êtes assignés en tant qu\'administrateur du projet "{projectTitle}".',
    'You have been mentioned in a comment' => 'Vous êtes mentionnés dans un commentaire',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Vous avez été notifié dans un commentaire pour l\'écran "{screenTitle}" dans le projet "{projectTitle}":',
    'You have been removed from project "{projectTitle}".' => 'Vous avez été retiré du projet "{projectTitle}":',
    'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Vous avez un commentaire non lu pour l\'écran "{screenTitle}" du projet "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Votre compte Presentator a été créé avec succès.',
    '{projectTitle} preview' => 'Aperçu de {projectTitle}',
);
