<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Allineamento',
    'Allow comments' => 'Consenti commenti',
    'Allow guideline' => 'Consenti linee guida',
    'Archived' => 'Archiviato',
    'Avatar' => 'Avatar',
    'Background' => 'Sfondo',
    'Client' => 'Cliente',
    'Code' => 'Codice',
    'Delete avatar' => 'Elimina avatar',
    'Description' => 'Descrizione',
    'Email' => 'Email',
    'Email address domain is not allowed.' => 'Il dominio di questo indirizzo email non è ammesso.',
    'Failed to authorize.' => 'Autorizzazione fallita.',
    'File' => 'File',
    'First name' => 'Nome',
    'Fixed footer' => 'Footer fisso',
    'Fixed header' => 'Header fisso',
    'From' => 'Da',
    'Height' => 'Altezza',
    'Horizontal position' => 'Posizione orizzontale',
    'Invalid HEX color code.' => 'Codice colore esadecimale non valido.',
    'Invalid formatted value.' => 'Valore non valido.',
    'Invalid guideline section ID.' => 'ID sezione linee guida non valido.',
    'Invalid hotspot template ID.' => 'ID template hotspot non valido.',
    'Invalid login credentials.' => 'Credenziali d\'accesso non valide.',
    'Invalid or expired token.' => 'Token non valido o scaduto.',
    'Invalid password.' => 'Password non valida.',
    'Invalid primary comment ID.' => 'ID commento primario non valido.',
    'Invalid project ID.' => 'ID progetto non valido.',
    'Invalid prototype ID.' => 'ID prototipo non valido.',
    'Invalid screen ID.' => 'ID schermata non valido.',
    'Last name' => 'Cognome',
    'Left' => 'Sinistra',
    'Message' => 'Messaggio',
    'New password' => 'Nuova password',
    'New password confirm' => 'Conferma nuova password',
    'Notify on each comment' => 'Notifica ad ogni commento',
    'Notify on mention' => 'Notifica quando vieni menzionato',
    'Old password' => 'Vecchia password',
    'Oops, an error occurred while processing your request.' => 'Ops, qualcosa è andato storto durante l\'esecuzione della tua richiesta.',
    'Order' => 'Ordine',
    'Overlay position' => 'Posizione sovrimpressione',
    'Password' => 'Password',
    'Password confirm' => 'Conferma password',
    'Passwords don\'t match.' => 'Le password non coincidono.',
    'Prototypes' => 'Ptorotipi',
    'Reply to' => 'Rispondi a',
    'Scale factor' => 'Fattore di scala',
    'Screen' => 'Schermata',
    'Status' => 'Stato',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'La risorsa che stai cercando non esiste o non è momentaneamente disponibile.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'Questo indirizzo email coincide con un amministratore del progetto. Gli amministratori del progetto sono invitati a commentare usando l\'area amministrativa.',
    'Title' => 'Titolo',
    'Token' => 'Token',
    'Top' => 'Sopra',
    'Transition' => 'Transizione',
    'Type' => 'Digita',
    'Url' => 'Url',
    'User with such email address already exist.' => 'Esiste già un utente con questo indirizzo email.',
    'Vertical position' => 'Posizione verticale',
    'Width' => 'Larghezza',
    'You are not allowed to perform this request.' => 'Non sei autorizzato ad effettuare questa richiesta.',
    'You cannot unlink the only user of the project.' => 'Non puoi rimuovere l\'unico utente del progetto.',
);
