<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Attivazione account',
    'Activate account' => 'Attiva account',
    'Administrator assignment' => 'Assegnazione amministratore',
    'Administrator discharge' => 'Revoca amministrazione',
    'Best Regards' => 'Cordiali saluti',
    'Click on the button below for detail view and other options:' => 'Clicca sul pulsante sottostante per opzioni e dettagli:',
    'Click on the button below to activate your account:' => 'Clicca il pulsante sottostante per attivare il tuo account:',
    'Click on the button below to explore the project:' => 'Clicca sul pulsante sottostante per esplorare il progetto',
    'Confirm email address change' => 'Conferma il cambio d\'indirizzo email',
    'Detail view' => 'Vedi dettagli',
    'Email change confirmation' => 'Conferma di cambio indirizzo email',
    'Explore project' => 'Esplora progetto',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Per ragioni di sicurezza, ti invitiamo a cambiare la password generata il prima possibile.',
    'Hello' => 'Ciao',
    'Password reset request' => 'Richiesta di cambio password',
    'Presentator Team' => 'Il team di Presentator',
    'Reset password' => 'Reimposta password',
    'Successfully authenticated' => 'Autenticazione avvenuta con successo',
    'Thank you for your registration at Presentator.' => 'Grazie per esserti registrato a Presentator.',
    'To update your password, click the button below:' => 'Clicca sul pulsante sottostante per aggiornare la tua password:',
    'Unread comment' => 'Commento non letto',
    'View design' => 'Vedi design',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Abbiamo generato una password casuale per il tuo account per permetterti di accedere senza l\'ausilio di autenticazioni di terze parti.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Abbiamo ricevuto una richiesta di cambio indirizzo email del tuo account Presentator da {oldEmail} a {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Abbiamo ricevuto una richiesta per reimpostare la password del tuo account.',
    'You are invited to review the design for project "{projectTitle}".' => 'Sei stato invitato a visualizzare il design del progetto "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'Sei stato assegnato come amministratore del progetto "{projectTitle}".',
    'You have been mentioned in a comment' => 'Sei stato menzionato in un commento',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Sei stato menzionato in un commento nella schermata "{screenTitle}" del progetto "{projectTitle}":',
    'You have been removed from project "{projectTitle}".' => 'Sei stato rimosso dal progetto "{projectTitle}".',
    'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Hai un commento non letto nella schermata "{screenTitle}" del progetto "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Il tuo account Presentator è stato creato con successo.',
    '{projectTitle} preview' => 'Anteprima {projectTitle}',
);
