<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Препоръчително е да подмениш автоматично генерираната парола възможно най-скоро.',
    'Successfully authenticated' => 'Успешна регистрация',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Автоматично генерирахме парола за твоя акаунт, за да може да го ползваш без нуждата от авторизиране от 3-та страна.',
    'A new comment was left for project "{projectTitle}".' => 'Нов коментар беше оставен към проект "{projectTitle}".',
    'Account activation' => 'Активиране на профил',
    'Activate account' => 'Активиране на профил',
    'Administrator assignment' => 'Назначаване като администратор',
    'Administrator discharge' => 'Премахване на администраторски права към проект',
    'Best Regards' => 'Поздрави',
    'Click on the button below for detail view and other options:' => 'Кликни на бутона по-долу за детайлен преглед и други опции:',
    'Click on the button below to activate your account:' => 'Кликни на бутона по-долу, за да активираш профила си:',
    'Click on the button below to explore the project:' => 'Кликни на бутона по-долу, за да разгледаш проекта:',
    'Click on the button below to reset it and set a new one:' => 'Кликни на бутона по-долу, за да продължиш:',
    'Confirm email address change' => 'Потвърди смяната на имейл адреса',
    'Detail view' => 'Детайлен преглед',
    'Email change request' => 'Промяна на имейл адреса',
    'Explore project' => 'Преглед на проекта',
    'From' => 'От',
    'Hello' => 'Здравей',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'При нужда от допълнителна помощ, може да се свържеш с нас на {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Ако смяташ, че това съобщение е грешка или имаш нужда от допълнителна помощ, може да се свържеш с нас на {supportEmail}.',
    'Message' => 'Съобщение',
    'New comment' => 'Нов коментар',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'п.п. Ако не искаш да получаваш повече подобни известия, може да изключиш опцията от настройките на профила си.',
    'Password reset request' => 'Заявка за смяна на парола',
    'Presentator Team' => 'Екипът на Presentator',
    'Reset password' => 'Смяна на парола',
    'Screen' => 'Екран',
    'Thank you for registering to {appLink}.' => 'Благодарим ти за регистрацията в {appLink}.',
    'View project' => 'Виж проекта',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Получихме запитване за смяна на имейл адреса на профила ти в Presentator от {oldEmail} на {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Получихме заявка за смяна на паролата на твоя профил.',
    'You are assigned as admin to project "{projectTitle}".' => 'Назначен си като администатор към проект "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Поканен си да разгледаш дизайна на "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Премахнати са администраторските ти права към проект "{projectTitle}".',
    'You have been mentioned in a comment' => 'Споменаване в коментар',
    'You have been mentioned in a comment for project "{projectTitle}".' => 'Споменат си в коментар към проект "{projectTitle}."',
    '{projectTitle} preview' => '{projectTitle} преглед',
);
