<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'A new comment was left for project "{projectTitle}".' => 'Нов коментар беше оставен към проект "{projectTitle}"',
    'Activate account' => 'Активиране на профил',
    'Best Regards' => 'Поздрави',
    'Click on the button below for detail view and other options:' => 'Кликни на бутона по-долу за детайлен преглед и други опции:',
    'Click on the button below to activate your account:' => 'Кликни на бутона по-долу, за да активираш профила си:',
    'Click on the button below to continue:' => 'Кликни на бутона по-долу, за да продължиш:',
    'Click on the button below to explore the project:' => 'Кликни на бутона по-долу, за да разгледаш проекта:',
    'Detail view' => 'Детайлен преглед',
    'Explore project' => 'Преглед на проекта',
    'From' => 'От',
    'Hello' => 'Здравей',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'При нужда от допълнителна помощ, може да се свържеш с нас на {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Ако смяташ, че това съобщение е грешка или имаш нужда от допълнителна помощ, може да се свържеш с нас на {supportEmail}.',
    'Message' => 'Съобщение',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'п.п. Ако не искаш да получаваш повече подобни известия, може да изключиш опцията от настройките на профила си.',
    'Presentator Team' => 'Екипът на Presentator',
    'Reset password' => 'Смяна на парола',
    'Screen' => 'Екран',
    'Thank you for registering to {appLink}.' => 'Благодарим ти за регистрацията в {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'За да може да се логваш без да е необходима Facebook аутентикация, автоматично сме задали следната парола на твоя профил:',
    'View project' => 'Виж проекта',
    'We\'ve received a request to reset your account password.' => 'Получихме заявка за смяна на паролата на твоя профил.',
    'Click on the button below to reset it and set a new one:' => 'Кликни на бутона по-долу, за да продължиш:',
    'You are assigned as admin to project "{projectTitle}".' => 'Назначен си като администатор към проект "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Поканен си да разгледаш дизайна на "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Премахнати са администраторските ти права към проект "{projectTitle}".',
    'You have successfully registered via Facebook.' => 'Успешна регистрация чрез Facebook.',
);
