<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'A new comment was left for project "{projectTitle}".' => 'Нов коментар беше оставен към проект "{projectTitle}"',
    'Activate account' => 'Активирай профила',
    'Best Regards' => 'Поздрави',
    'Click on the button below for detail view and other options:' => 'Кликнете на бутона по-долу за детайлен преглед и други опции:',
    'Click on the button below to activate your account:' => 'Кликнете на бутона по-долу, за да активирате профила си:',
    'Click on the button below to continue:' => 'Кликнете на бутона по-долу, за да продължите:',
    'Click on the button below to explore the project:' => 'Кликнете на бутона по-долу, за да разгледате проекта:',
    'Detail view' => 'Детайлен преглед',
    'Explore project' => 'Преглед на проекта',
    'From' => 'От',
    'Hello' => 'Здравейте',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Ако имаге нужда от допълнителна помощ, може да се свържете с нас на {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Ако смятате, че това съобщение е грешка или имате нужда от допълнителна помощ, може да се свържете с нас на {supportEmail}.',
    'Message' => 'Съобщение',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator.io account settings page.' => 'п.п. Ако не искате да получавате повече подобни известия, може да изключите опцията от настройките на профилната ви страница в платформата.',
    'Presentator.io Team' => 'Екипът на Presentator.io',
    'Reset password' => 'Смяна на парола',
    'Screen' => 'Екран',
    'Thank you for registering to {appLink}.' => 'Благодарим ви за регистрацията в {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'За да може да се логвате без да е необходима Facebook аутентикация, автоматично сме задали следната парола на вашия профил:',
    'View project' => 'Виж проекта',
    'We\'ve received a request to reset your account password.' => 'Получихме заявка за смяна на вашата парола.',
    'Click on the button below to reset it and set a new one:' => 'Кликнете на бутона по-долу, за да продължите:',
    'You are assigned as admin to project "{projectTitle}".' => 'Добавен сте като администратор към проект "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Поканени сте да разгледате дизайна на "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Вие бяхте премахнати като администратор към проект "{projectTitle}".',
    'You have successfully registered via Facebook.' => 'Успешно се регистрирахте с Facebook.',
);
