<?php
use \common\models\ScreenComment;

return [
    // screen 1001
    [
        'id'        => 1001,
        'replyTo'   => null,
        'screenId'  => 1001,
        'from'      => 'some_test_email@presentator.io',
        'message'   => 'Lorem ipsum dolor sit amet...',
        'posX'      => 200,
        'posY'      => 100,
        'status'    => ScreenComment::STATUS_PENDING,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
    [
        'id'        => 1002,
        'replyTo'   => null,
        'screenId'  => 1001,
        'from'      => 'some_test_email@presentator.io',
        'message'   => 'Lorem ipsum dolor sit amet...',
        'posX'      => 220,
        'posY'      => 150,
        'status'    => ScreenComment::STATUS_RESOLVED,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
    [
        'id'        => 1003,
        'replyTo'   => 1002,
        'screenId'  => 1001,
        'from'      => 'test2@presentator.io',
        'message'   => 'Reply message...',
        'posX'      => 220,
        'posY'      => 150,
        'status'    => ScreenComment::STATUS_PENDING,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
    // screen 1003
    [
        'id'        => 1004,
        'replyTo'   => null,
        'screenId'  => 1003,
        'from'      => 'test3@presentator.io',
        'message'   => 'Comment from the author...',
        'posX'      => 12,
        'posY'      => 59,
        'status'    => ScreenComment::STATUS_PENDING,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
    // screen 1004
    [
        'id'        => 1005,
        'replyTo'   => null,
        'screenId'  => 1004,
        'from'      => 'test3@presentator.io',
        'message'   => 'Comment target',
        'posX'      => 100,
        'posY'      => 50,
        'status'    => ScreenComment::STATUS_PENDING,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
    [
        'id'        => 1006,
        'replyTo'   => 1005,
        'screenId'  => 1004,
        'from'      => 'loremipsum@presentator.io',
        'message'   => 'Comment reply 1',
        'posX'      => 100,
        'posY'      => 50,
        'status'    => ScreenComment::STATUS_PENDING,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
    [
        'id'        => 1007,
        'replyTo'   => 1005,
        'screenId'  => 1004,
        'from'      => 'test5@presentator.io',
        'message'   => 'Comment reply 2',
        'posX'      => 100,
        'posY'      => 50,
        'status'    => ScreenComment::STATUS_PENDING,
        'createdAt' => 1488526394,
        'updatedAt' => 1488526394,
    ],
];
