<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */

$params = array_merge(
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'color'        => null,
    'interactive'  => true,
    'help'         => null,
    'sourcePath'   => realpath(__DIR__ . '/../../'),
    'messagePath'  => realpath(__DIR__ . '/../messages'),
    'languages'    => $params['languages'],
    'translator'   => 'Yii::t',
    'sort'         => false,
    'overwrite'    => true,
    'removeUnused' => false,
    'markUnused'   => true,
    'except'       => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/docs',
        '/docker',
        '/vendor',
        '/messages',
        '/BaseYii.php',
        '/common/tests',
        '/app/tests',
        '/api/tests',
    ],
    'only' => [
        '*.php',
    ],
    'format'           => 'php',
    'catalog'          => 'messages',
    'ignoreCategories' => [],
    // 'db'                 => 'db',
    // 'sourceMessageTable' => '{{%source_message}}',
    // 'messageTable'       => '{{%message}}',
];
