<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'A new comment was left for project "{projectTitle}".' => 'Ein neuer Kommentar wurde zum Projekt "{projectTitle}" hinterlassen.',
    'Account activation' => 'Kontoaktivierung',
    'Activate account' => 'Konto aktivieren',
    'Administrator assignment' => 'Administratorverknüpfung',
    'Administrator discharge' => 'Verknüpfung eines Administrators aufheben',
    'Best Regards' => 'Beste Grüße',
    'Click on the button below for detail view and other options:' => 'Klicke auf den nachfolgenden Button für die Detailansicht und weitere Optionen:',
    'Click on the button below to activate your account:' => 'Klicke auf den nachfolgenden Button um dein Konto zu aktivieren:',
    'Click on the button below to continue:' => 'Klicke auf den nachfolgenden Button um fortzufahren:',
    'Click on the button below to explore the project:' => 'Klicke auf den nachfolgenden Button um das Projekt anzusehen:',
    'Click on the button below to reset it and set a new one:' => 'Klicke auf den nachfolgenden Button um es zurückzusetzen und ein neues einzurichten:',
    'Detail view' => 'Detailansicht',
    'Explore project' => 'Projekt ansehen',
    'From' => 'Von',
    'Hello' => 'Hallo',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Wenn du weitere Hilfe benötigst, kontaktiere und unter {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Wenn du denkst diese E-Mail wurde fälschlicherweise versendet oder wenn du weitere Hilfe benötigst, kontaktiere und unter {supportEmail}.',
    'Message' => 'Nachricht',
    'New comment' => 'Neuer Kommentar',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S.: Wenn du keine Benachrichtigungen mehr zu Kommentaren erhalten möchtest, kannst du deine Einstellungen hierzu unter deinen Presentator Kontoeinstellungen anpassen.',
    'Password reset request' => 'Passwort zurücksetzen',
    'Presentator Team' => 'Presentator Team',
    'Registered with Facebook' => 'Registriert mit Facebook',
    'Reset password' => 'Passwort zurücksetzen',
    'Screen' => 'Screen',
    'Thank you for registering to {appLink}.' => 'Danke für deine Registrierung auf {appLink}.',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => 'Damit du dich ohne die Facebook Authentifizierung anmelden kannst, haben wir ein zufällig generiertes Passwort für dein Konto gesetzt:',
    'View project' => 'Projekt ansehen',
    'We\'ve received a request to reset your account password.' => 'Wir haben eine Anfrage zum Zurücksetzen deines Passworts erhalten. ',
    'You are assigned as admin to project "{projectTitle}".' => 'Du wurdest dem Projekt "{projectTitle}" als Administrator zugewiesen. ',
    'You are invited to review the design for "{projectTitle}".' => 'Du wurdest eingeladen das Design von "{projectTitle}" zu begutachten. ',
    'You are no longer an administrator to project "{projectTitle}".' => 'Du bist nicht länger ein Administrator des Projekts "{projectTitle}" ',
    'You have successfully registered via Facebook.' => 'Du hast dich erfolgreich mit Facebook registriert.',
    '{projectTitle} preview' => '{projectTitle} Vorschau',
);
