<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Подравняване',
    'Allow comments' => 'Разреши коментари',
    'Allow guideline' => 'Разреши guideline',
    'Archived' => 'Архивиран',
    'Avatar' => 'Аватар',
    'Background' => 'Фон',
    'Client' => 'Клиент',
    'Code' => 'Код',
    'Delete avatar' => 'Изтриване на аватар',
    'Description' => 'Описание',
    'Email' => 'Имейл',
    'Email address domain is not allowed.' => 'Домейнът на имейл адреса е невалиден или забранен.',
    'Failed to authorize.' => 'Неуспешно ауторизиране.',
    'File' => 'Файл',
    'First name' => 'Име',
    'Fixed footer' => 'Фиксиран футър',
    'Fixed header' => 'Фиксиран хедър',
    'From' => 'От',
    'Height' => 'Височина',
    'Horizontal position' => 'Хоризонтална позиция',
    'Invalid HEX color code.' => 'Невалиден HEX код.',
    'Invalid formatted value.' => 'Невалидно форматирана стойност.',
    'Invalid guideline section ID.' => 'Невалидно ID.',
    'Invalid hotspot template ID.' => 'Невалидно ID.',
    'Invalid login credentials.' => 'Невалидни данни за вход.',
    'Invalid or expired token.' => 'Невалиден или изтекъл код.',
    'Invalid password.' => 'Невалидна парола.',
    'Invalid primary comment ID.' => 'Невалидно ID.',
    'Invalid project ID.' => 'Невалидно ID.',
    'Invalid prototype ID.' => 'Невалидно ID.',
    'Invalid screen ID.' => 'Невалидно ID.',
    'Last name' => 'Фамилия',
    'Left' => 'Left',
    'Message' => 'Съобщение',
    'New password' => 'Нова парола',
    'New password confirm' => 'Потвърждение на новата парола',
    'Notify on each comment' => 'Извести при всеки коментар',
    'Notify on mention' => 'Извести само при споменаване',
    'Old password' => 'Стара парола',
    'Order' => 'Подредба',
    'Overlay position' => 'Позиция на оверлейа',
    'Password' => 'Парола',
    'Password confirm' => 'Потвърждение на паролата',
    'Passwords don\'t match.' => 'Паролите не съвпадат',
    'Prototypes' => 'Прототипи',
    'Reply to' => 'Отговор на',
    'Scale factor' => 'Скейлинг фактор',
    'Screen' => 'Екран',
    'Status' => 'Статус',
    'Oops, an error occurred while processing your request.' => 'Упс, възникна грешка при обработката на твоята заявка.',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'Ресурсът, който търсите, не съществува или е временно недостъпен.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'Има администратор с такъв имейл. Администраторите на проект трябва да използват формата от админ панела, за да коментират.',
    'Title' => 'Заглавие',
    'Token' => 'Код',
    'Top' => 'Top',
    'Transition' => 'Transition',
    'Type' => 'Тип',
    'Url' => 'Url',
    'User with such email address already exist.' => 'Съществува потребител с такъв имейл адрес.',
    'Vertical position' => 'Вертикална позиция',
    'Width' => 'Ширина',
    'You are not allowed to perform this request.' => 'Нямаш достатъчно права да извършиш текущата заявка.',
    'You cannot unlink the only user of the project.' => 'Не може да премахнеш единствения администратор на проекта.',
);
