<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Активиране на профил',
    'Activate account' => 'Активиране на профил',
    'Administrator assignment' => 'Назначаване като администратор',
    'Administrator discharge' => 'Премахнати администраторски права към проект',
    'Best Regards' => 'Поздрави',
    'Click on the button below for detail view and other options:' => 'Кликни на бутона по-долу за детайлен преглед и други опции:',
    'Click on the button below to activate your account:' => 'Кликни на бутона по-долу, за да активираш профила си:',
    'Click on the button below to explore the project:' => 'Кликни на бутона по-долу, за да разгледаш проекта:',
    'Confirm email address change' => 'Потвърди смяната на имейл адреса',
    'Detail view' => 'Детайлен преглед',
    'Email change confirmation' => 'Промяна на имейл адрес',
    'Explore project' => 'Разгледай проекта',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Препоръчително е да подмениш автоматично генерираната парола възможно най-скоро.',
    'Hello' => 'Здравей',
    'Password reset request' => 'Заявка за смяна на парола',
    'Presentator Team' => 'Екипът на Presentator',
    'Reset password' => 'Смяна на парола',
    'Successfully authenticated' => 'Успешна ауторизация',
    'Thank you for your registration at Presentator.' => 'Благодарим ти за регистрацията в Presentator.',
    'To update your password, click the button below:' => 'За да промениш паролата си, кликни на бутона по-долу:',
    'Unread comment' => 'Непрочен коментар',
    'View design' => 'Разгледай дизайна',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Автоматично генерирахме парола за твоя профил, за да може да го ползваш без нуждата от ауторизация на 3-та страна.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Получихме запитване за смяна на имейл адреса на профила ти в Presentator от {oldEmail} на {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Получихме заявка за смяна на паролата на твоя профил.',
    'You are invited to review the design for project "{projectTitle}".' => 'Поканен си да разгледаш дизайна на проект "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'Назначен си като администратор към проект "{projectTitle}".',
    'You have been removed from project "{projectTitle}".' => 'Премахнати са администраторските ти права към проект "{projectTitle}".',
    'You have been mentioned in a comment' => 'Споменаване в коментар',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Споменат си в коментар за екран "{screenTitle}" към проект "{projectTitle}":',
    'You have unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Имаш непрочетен коментар за екран "{screenTitle}" към проект "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Твоят профил в Presentator беше успешно създаден.',
    '{projectTitle} preview' => '{projectTitle} преглед',
);
