<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'For security reasons, we encourage you to change the generated password as soon as possible.',
    'Successfully authenticated' => 'Successfully authenticated',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.',
    'A new comment was left for project "{projectTitle}".' => 'A new comment was left for project "{projectTitle}".',
    'Account activation' => 'Account activation',
    'Activate account' => 'Activate account',
    'Administrator assignment' => 'Administrator assignment',
    'Administrator discharge' => 'Administrator discharge',
    'Best Regards' => 'Best Regards',
    'Click on the button below for detail view and other options:' => 'Click on the button below for detail view and other options:',
    'Click on the button below to activate your account:' => 'Click on the button below to activate your account:',
    'Click on the button below to explore the project:' => 'Click on the button below to explore the project:',
    'Click on the button below to reset it and set a new one:' => 'Click on the button below to reset it and set a new one:',
    'Confirm email address change' => 'Confirm email address change',
    'Detail view' => 'Detail view',
    'Email change request' => 'Email change request',
    'Explore project' => 'Explore project',
    'From' => 'From',
    'Hello' => 'Hello',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'If you need any further help don\'t hesitate to contact us at {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.',
    'Message' => 'Message',
    'New comment' => 'New comment',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.',
    'Password reset request' => 'Password reset request',
    'Presentator Team' => 'Presentator Team',
    'Reset password' => 'Reset password',
    'Screen' => 'Screen',
    'Thank you for registering to {appLink}.' => 'Thank you for registering to {appLink}.',
    'View project' => 'View project',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'We\'ve received a request to reset your account password.',
    'You are assigned as admin to project "{projectTitle}".' => 'You are assigned as admin to project "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'You are invited to review the design for "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'You are no longer an administrator to project "{projectTitle}".',
    'You have been mentioned in a comment' => 'You have been mentioned in a comment',
    'You have been mentioned in a comment for project "{projectTitle}".' => 'You have been mentioned in a comment for project "{projectTitle}".',
    '{projectTitle} preview' => '{projectTitle} preview',
);
