<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Alignment',
    'Allow comments' => 'Allow comments',
    'Allow guideline' => 'Allow guideline',
    'Archived' => 'Archived',
    'Avatar' => 'Avatar',
    'Background' => 'Background',
    'Client' => 'Client',
    'Code' => 'Code',
    'Delete avatar' => 'Delete avatar',
    'Description' => 'Description',
    'Email' => 'Email',
    'Email address domain is not allowed.' => 'Email address domain is not allowed.',
    'Failed to authorize.' => 'Failed to authorize.',
    'File' => 'File',
    'First name' => 'First name',
    'Fixed footer' => 'Fixed footer',
    'Fixed header' => 'Fixed header',
    'From' => 'From',
    'Height' => 'Height',
    'Horizontal position' => 'Horizontal position',
    'Invalid HEX color code.' => 'Invalid HEX color code.',
    'Invalid formatted value.' => 'Invalid formatted value.',
    'Invalid guideline section ID.' => 'Invalid guideline section ID.',
    'Invalid hotspot template ID.' => 'Invalid hotspot template ID.',
    'Invalid login credentials.' => 'Invalid login credentials.',
    'Invalid or expired token.' => 'Invalid or expired token.',
    'Invalid password.' => 'Invalid password.',
    'Invalid primary comment ID.' => 'Invalid primary comment ID.',
    'Invalid project ID.' => 'Invalid project ID.',
    'Invalid prototype ID.' => 'Invalid prototype ID.',
    'Invalid screen ID.' => 'Invalid screen ID.',
    'Last name' => 'Last name',
    'Left' => 'Left',
    'Message' => 'Message',
    'New password' => 'New password',
    'New password confirm' => 'New password confirm',
    'Notify on each comment' => 'Notify on each comment',
    'Notify on mention' => 'Notify on mention',
    'Old password' => 'Old password',
    'Oops, an error occurred while processing your request.' => 'Oops, an error occurred while processing your request.',
    'Order' => 'Order',
    'Overlay position' => 'Overlay position',
    'Password' => 'Password',
    'Password confirm' => 'Password confirm',
    'Passwords don\'t match.' => 'Passwords don\'t match.',
    'Prototypes' => 'Prototypes',
    'Reply to' => 'Reply to',
    'Scale factor' => 'Scale factor',
    'Screen' => 'Screen',
    'Status' => 'Status',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'The resource you are looking for does not exist or is temporary unavailable.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'There is a project admin with such email address. Project admins should use the admin area to comment.',
    'Title' => 'Title',
    'Token' => 'Token',
    'Top' => 'Top',
    'Transition' => 'Transition',
    'Type' => 'Type',
    'Url' => 'Url',
    'User with such email address already exist.' => 'User with such email address already exist.',
    'Vertical position' => 'Vertical position',
    'Width' => 'Width',
    'You are not allowed to perform this request.' => 'You are not allowed to perform this request.',
    'You cannot unlink the only user of the project.' => 'You cannot unlink the only user of the project.',
);
