<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Account activation',
    'Activate account' => 'Activate account',
    'Administrator assignment' => 'Administrator assignment',
    'Administrator discharge' => 'Administrator discharge',
    'Best Regards' => 'Best Regards',
    'Click on the button below for detail view and other options:' => 'Click on the button below for detail view and other options:',
    'Click on the button below to activate your account:' => 'Click on the button below to activate your account:',
    'Click on the button below to explore the project:' => 'Click on the button below to explore the project:',
    'Confirm email address change' => 'Confirm email address change',
    'Detail view' => 'Detail view',
    'Email change confirmation' => 'Email change confirmation',
    'Explore project' => 'Explore project',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'For security reasons, we encourage you to change the generated password as soon as possible.',
    'Hello' => 'Hello',
    'Password reset request' => 'Password reset request',
    'Presentator Team' => 'Presentator Team',
    'Reset password' => 'Reset password',
    'Successfully authenticated' => 'Successfully authenticated',
    'Thank you for your registration at Presentator.' => 'Thank you for your registration at Presentator.',
    'To update your password, click the button below:' => 'To update your password, click the button below:',
    'Unread comment' => 'Unread comment',
    'View design' => 'View design',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'We\'ve received a request to reset your account password.',
    'You are invited to review the design for project "{projectTitle}".' => 'You are invited to review the design for project "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'You have been assigned as administrator to project "{projectTitle}".',
    'You have been mentioned in a comment' => 'You have been mentioned in a comment',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":',
    'You have been removed from project "{projectTitle}".' => 'You have been removed from project "{projectTitle}".',
    'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Your Presentator account was successfully created.',
    '{projectTitle} preview' => '{projectTitle} preview',
);
