<?php
use presentator\api\models\User;

return [
    [
        'id'                 => 1001,
        'type'               => User::TYPE['REGULAR'],
        'email'              => 'test1@example.com',
        'passwordHash'       => '$2a$06$D.vvwAuHJKg37EXIQnY39ezf2U23YcW2KAgK91UCn9XMtg5f4q6Aa', // 123456,
        'passwordResetToken' => null,
        'authKey'            => '24vWsdaU7dCVkpXEG4nDhj1aplzhfdas',
        'firstName'          => 'Joe',
        'lastName'           => '',
        'avatarFilePath'     => null,
        'status'             => User::STATUS['INACTIVE'],
        'createdAt'          => '2019-06-28 01:00:00',
        'updatedAt'          => '2019-06-28 01:00:00',
    ],
    [
        'id'                 => 1002,
        'type'               => User::TYPE['REGULAR'],
        'email'              => 'test2@example.com',
        'passwordHash'       => '$2a$06$D.vvwAuHJKg37EXIQnY39ezf2U23YcW2KAgK91UCn9XMtg5f4q6Aa', // 123456,
        'passwordResetToken' => '124vWsdaU7dCVkpXEG4nDhjaplzhfdas_' . strtotime('+1 hour'), // valid token
        'authKey'            => 'daU7dCVkpXEG4nDhj124vWsaplzhfdas',
        'firstName'          => 'Bob',
        'lastName'           => 'Bobrev',
        'avatarFilePath'     => null,
        'status'             => User::STATUS['ACTIVE'],
        'createdAt'          => '2019-06-28 02:00:00',
        'updatedAt'          => '2019-06-28 02:00:00',
    ],
    [
        'id'                 => 1003,
        'type'               => User::TYPE['SUPER'],
        'email'              => 'test3@example.com',
        'passwordHash'       => '$2a$06$D.vvwAuHJKg37EXIQnY39ezf2U23YcW2KAgK91UCn9XMtg5f4q6Aa', // 123456,
        'passwordResetToken' => 'dCVkpXEG4nDhjaplzh124vWsdaU7fdas_' . strtotime('-1 day'), // expired token
        'authKey'            => 'dahj124vWsaplzhfdasU7dCVkpXEG4nD',
        'firstName'          => 'Jun',
        'lastName'           => 'Junev',
        'avatarFilePath'     => null,
        'status'             => User::STATUS['ACTIVE'],
        'createdAt'          => '2019-06-28 03:00:00',
        'updatedAt'          => '2019-06-28 03:00:00',
    ],
    [
        'id'                 => 1004,
        'type'               => User::TYPE['REGULAR'],
        'email'              => 'test4@example.com',
        'passwordHash'       => '$2a$06$D.vvwAuHJKg37EXIQnY39ezf2U23YcW2KAgK91UCn9XMtg5f4q6Aa', // 123456,
        'passwordResetToken' => null,
        'authKey'            => 'Cdahj124vWsaplzhfdasU7dVkpXEG4nD',
        'firstName'          => null,
        'lastName'           => null,
        'avatarFilePath'     => null,
        'status'             => User::STATUS['ACTIVE'],
        'createdAt'          => '2019-06-28 04:00:00',
        'updatedAt'          => '2019-06-28 04:00:00',
    ],
    [
        'id'                 => 1005,
        'type'               => User::TYPE['REGULAR'],
        'email'              => 'test5@example.com',
        'passwordHash'       => '$2a$06$D.vvwAuHJKg37EXIQnY39ezf2U23YcW2KAgK91UCn9XMtg5f4q6Aa', // 123456,
        'passwordResetToken' => null,
        'authKey'            => '24vWsaplzhfdasU7dahj1dCVkpXEG4nD',
        'firstName'          => null,
        'lastName'           => 'Juniper',
        'avatarFilePath'     => null,
        'status'             => User::STATUS['ACTIVE'],
        'createdAt'          => '2019-06-27 00:00:00',
        'updatedAt'          => '2019-06-27 00:00:00',
    ],
];
