<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'For security reasons, we encourage you to change the generated password as soon as possible.' => '',
    'Successfully authenticated' => '',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => '',
    'Click on the button below to continue:' => '@@Kliko mbi butonin më poshtë për të vazhduar:@@',
    'Registered with Facebook' => '@@Regjistruar me Facebook@@',
    'To be able to login without the need of Facebook authentication, we have set a random password for your account:' => '@@Për tu kyçur pa nevojën e vertëtimit nëpërmjet Facebook, ne vendosëm një fjalëkalim të rastësishëm për llogarinë tënde:@@',
    'You have successfully registered via Facebook.' => '@@Je regjistruar me sukses nëpërmjet Facebook.@@',
    'A new comment was left for project "{projectTitle}".' => 'Një koment i ri është lënë në projektin "{projectTitle}".',
    'Account activation' => 'Aktivizim llogarie',
    'Activate account' => 'Aktivizo llogarinë',
    'Administrator assignment' => 'Përzgjedhje administratori',
    'Administrator discharge' => 'Shkarkim administratori',
    'Best Regards' => 'Gjithë të mirat',
    'Click on the button below for detail view and other options:' => 'Kliko mbi butoni më poshtë për pamjen e detajuar dhe zgjedhje të tjera:',
    'Click on the button below to activate your account:' => 'Kliko mbi butonin më poshtë për të aktivizuar llogarinë tënde:',
    'Click on the button below to explore the project:' => 'Kliko mbi butonin më poshtë për të eksploruar projektin:',
    'Click on the button below to reset it and set a new one:' => 'Kliko mbi butonin më poshtë për ta rivendosur:',
    'Confirm email address change' => 'Konfirmo ndryshimin e adresës së email-it',
    'Detail view' => 'Pamja e detajuar',
    'Email change request' => 'Kërkesë për ndryshimin e email-it',
    'Explore project' => 'Eksploro projektin',
    'From' => 'Nga',
    'Hello' => 'Përshëndetje',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Nëse të duhet ndihmë më tej, mos hezito të na kontaktosh në {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Nëse mendon që ky mesazh është një gabim ose të duhet ndihmë më tej, mos heziton të na kontaktosh në {supportEmail}.',
    'Message' => 'Mesazh',
    'New comment' => 'Koment i ri',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S. Nëse nuk do të marrësh më njoftime komentesh, mund të përditësosh preferencat e tua në faqen e konfigurimeve në llogarinë tënde Presentator.',
    'Password reset request' => 'Kërkesë për rivendosje fjalëkalimi',
    'Presentator Team' => 'Skuadra Presentator',
    'Reset password' => 'Rivendos password',
    'Screen' => 'Imazh',
    'Thank you for registering to {appLink}.' => 'Faleminderit që u regjistruat në {appLink}.',
    'View project' => 'Shiko projektin',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Kemi marrë një kërkesë për ndryshimin e email-it të llogarisë tënde në Presentator nga {oldEmail} në {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Kemi marrë një kërkesë për rivendosjen e fjalëkalimit të llogarisë tënde.',
    'You are assigned as admin to project "{projectTitle}".' => 'Je caktuar si administrator për projektin "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Je i/e ftuar për të rishikuar dizajnin për "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Nuk je më një administrator në projektin "{projectTitle}".',
    'You have been mentioned in a comment' => 'Je përmendur në një koment',
    'You have been mentioned in a comment for project "{projectTitle}".' => 'Je përmendur në një koment për projektin "{projectTitle}".',
    '{projectTitle} preview' => '{projectTitle} parapamje',
];
