<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Z bezpečnostních důvodů doporučujeme, abyste co nejdříve změnili vygenerované heslo.',
    'Successfully authenticated' => 'Úspěšně ověřen',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Pro váš účet jsme vytvořili náhodné heslo, abyste mohli být přihlášeni bez nutnosti ověření třetí stranou.',
    'A new comment was left for project "{projectTitle}".' => 'Byl přidán nový komentář k projektu "{projectTitle}".',
    'Account activation' => 'Aktivace účtu',
    'Activate account' => 'Aktivovat účet',
    'Administrator assignment' => 'Přiřadit administrátora',
    'Administrator discharge' => 'Zrušit správce',
    'Best Regards' => 'S pozdravem',
    'Click on the button below for detail view and other options:' => 'Klepnutím na tlačítko níže zobrazíte podrobnosti a další možnosti:',
    'Click on the button below to activate your account:' => 'Kliknutím na tlačítko níže aktivujete svůj účet:',
    'Click on the button below to explore the project:' => 'Klikněte na tlačítko níže a prozkoumejte projekt:',
    'Click on the button below to reset it and set a new one:' => 'Kliknutím na tlačítko níže jej resetujete a nastavíte nové:',
    'Confirm email address change' => 'Potvrďte změnu e-mailové adresy',
    'Detail view' => 'Detailní pohled',
    'Email change request' => 'Žádost o změnu e-mailu',
    'Explore project' => 'Prozkoumejte projekt',
    'From' => 'Od',
    'Hello' => 'Ahoj',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Pokud potřebujete další pomoc, neváhejte a kontaktujte nás na adrese {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Pokud si myslíte, že tato zpráva je chyba nebo potřebujete další pomoc, neváhejte a kontaktujte nás na adrese {supportEmail}.',
    'Message' => 'Zpráva',
    'New comment' => 'Nový komentář',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S. Pokud nechcete dostávat oznámení o připomínkách, můžete aktualizovat své předvolby na stránce nastavení účtu Presentator.',
    'Password reset request' => 'Žádost o obnovení hesla',
    'Presentator Team' => 'Tým Presentatoru',
    'Reset password' => 'Obnovit heslo',
    'Screen' => 'Obrazovka',
    'Thank you for registering to {appLink}.' => 'Děkujeme, že jste se přihlásili do {appLink}.',
    'View project' => 'Zobrazit projekt',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Dostali jsme žádost o změnu e-mailové adresy účtu Presentator z {oldEmail} na {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Obdrželi jsme žádost o obnovení hesla vašeho účtu.',
    'You are assigned as admin to project "{projectTitle}".' => 'Jste přiřazen/a jako administrátor projektu "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Jste zváni k prohlídce návrhu "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Nejste již správcem projektu "{projectTitle}".',
    'You have been mentioned in a comment' => 'Byl jste zmíněn v komentáři',
    'You have been mentioned in a comment for project "{projectTitle}".' => 'Byl jste zmíněn v komentáři k projektu "{projectTitle}".',
    '{projectTitle} preview' => 'Náhled {projectTitle}',
);
