<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Alignment',
    'Allow comments' => 'Allow comments',
    'Allow guideline' => 'Allow guideline',
    'Archived' => 'アーカイブする',
    'Avatar' => 'アバター',
    'Background' => '背景',
    'Client' => 'クライアント',
    'Code' => 'コード',
    'Delete avatar' => 'アバターの削除',
    'Description' => '説明',
    'Email' => 'Eメール',
    'Email address domain is not allowed.' => 'Email address domain is not allowed.',
    'Failed to authorize.' => '認証に失敗しました。',
    'File' => 'ファイル',
    'First name' => '名',
    'Fixed footer' => '修正したフッター',
    'Fixed header' => '修正したヘッダー',
    'From' => 'From',
    'Height' => '高さ',
    'Horizontal position' => '水平の位置',
    'Invalid HEX color code.' => '無効なHEXカラーコードです。',
    'Invalid formatted value.' => 'Invalid formatted value.',
    'Invalid guideline section ID.' => 'Invalid guideline section ID.',
    'Invalid hotspot template ID.' => 'Invalid hotspot template ID.',
    'Invalid login credentials.' => '無効なアカウントまたはパスワードです。',
    'Invalid or expired token.' => '無効または期限切れのトークンです。',
    'Invalid password.' => '無効なパスワードです。',
    'Invalid primary comment ID.' => 'Invalid primary comment ID.',
    'Invalid project ID.' => '無効なプロジェクトIDです。',
    'Invalid prototype ID.' => '無効なプロトタイプのIDです。',
    'Invalid screen ID.' => '無効なスクリーンのIDです。',
    'Last name' => '姓',
    'Left' => '左',
    'Message' => 'メッセージ',
    'New password' => '新しいパスワード',
    'New password confirm' => '新しいパスワードの確認',
    'Notify on each comment' => 'Notify on each comment',
    'Notify on mention' => 'Notify on mention',
    'Old password' => '古いパスワード',
    'Oops, an error occurred while processing your request.' => 'すみません。リクエストを処理中にエラーが発生しました。',
    'Order' => 'Order',
    'Overlay position' => 'オーバーレイの位置',
    'Password' => 'パスワード',
    'Password confirm' => 'パスワードの確認',
    'Passwords don\'t match.' => 'パスワードが一致しません。',
    'Prototypes' => 'プロトタイプ',
    'Reply to' => 'Reply to',
    'Scale factor' => 'Scale factor',
    'Screen' => 'スクリーン',
    'Status' => '状態',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'お探しのリソースは存在しないか、または一時的に利用不可能です。',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'There is a project admin with such email address. Project admins should use the admin area to comment.',
    'Title' => 'タイトル',
    'Token' => 'トークン',
    'Top' => 'トップ',
    'Transition' => 'Transition',
    'Type' => 'タイプ',
    'Url' => 'URL',
    'User with such email address already exist.' => 'User with such email address already exist.',
    'Vertical position' => '垂直の位置',
    'Width' => '横幅',
    'You are not allowed to perform this request.' => 'You are not allowed to perform this request.',
    'You cannot unlink the only user of the project.' => 'You cannot unlink the only user of the project.',
);
