<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'アカウントのアクティベーション',
    'Activate account' => 'アカウントをアクティベート',
    'Administrator assignment' => 'Administrator assignment',
    'Administrator discharge' => 'Administrator discharge',
    'Best Regards' => '敬具',
    'Click on the button below for detail view and other options:' => 'Click on the button below for detail view and other options:',
    'Click on the button below to activate your account:' => '以下のボタンをクリックして、あなたのアカウントをアクティベート:',
    'Click on the button below to explore the project:' => '以下のボタンをクリックして、プロジェクトを探す:',
    'Confirm email address change' => 'メールアドレス変更の確認',
    'Detail view' => '詳細ビュー',
    'Email change confirmation' => 'メールアドレスの変更確認',
    'Explore project' => 'プロジェクトを探す',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'セキュリティ上の理由から、生成されたパスワードをできるだけ早く変更することを推奨します。',
    'Hello' => 'こんにちは',
    'Password reset request' => 'パスワードリセットのリクエスト',
    'Presentator Team' => 'Presentatorチーム',
    'Reset password' => 'パスワードのリセット',
    'Successfully authenticated' => '認証に成功しました',
    'Thank you for your registration at Presentator.' => 'Presentatorへの新規アカウント登録、ありがとうございます。',
    'To update your password, click the button below:' => 'パスワードを更新するため、以下のボタンをクリックして下さい:',
    'Unread comment' => '未読のコメント',
    'View design' => 'デザインを見る',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'サードパーティのサービスによる認証無しでログインするために、あなたのアカウント向けにランダムなパスワードを生成しました。',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'あなたのPresentatorアカウントに登録していたメールアドレスを{oldEmail}から{newEmail}へ変更するリクエストを受理しました。',
    'We\'ve received a request to reset your account password.' => 'あなたのアカウントのパスワードリセットのリクエストを受理しました。',
    'You are invited to review the design for project "{projectTitle}".' => 'You are invited to review the design for project "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'You have been assigned as administrator to project "{projectTitle}".',
    'You have been mentioned in a comment' => 'あなたがコメントで言及されました',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'プロジェクト"{projectTitle}"のスクリーン"{screenTitle}"へのコメントで、あなたが言及されました:',
    'You have been removed from project "{projectTitle}".' => 'あなたはプロジェクト"{projectTitle}"から解任されました。',
    'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'プロジェクト"{projectTitle}"のスクリーン"{screenTitle}"に未読のコメントがあります:',
    'Your Presentator account was successfully created.' => 'あなたのPresentatorアカウントの作成に成功しました。',
    '{projectTitle} preview' => '{projectTitle}のプレビュー',
);
