<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Ausrichtung',
    'Allow comments' => 'Kommentare erlauben',
    'Allow guideline' => 'Guideline erlauben',
    'Archived' => 'Archiviert',
    'Avatar' => 'Avatar',
    'Background' => 'Hintergrund',
    'Client' => 'Client',
    'Code' => 'Code',
    'Delete avatar' => 'Avatar löschen',
    'Description' => 'Beschreibung',
    'Email' => 'E-Mail',
    'Email address domain is not allowed.' => 'E-Mail-Adress-Domain ist nicht erlaubt.',
    'Failed to authorize.' => 'Fehler bei der Authentifizierung.',
    'File' => 'Datei',
    'First name' => 'Vorname',
    'Fixed footer' => 'Footer fixieren',
    'Fixed header' => 'Header fixieren',
    'From' => 'Von',
    'Height' => 'Höhe',
    'Horizontal position' => 'Horizontale Position',
    'Invalid HEX color code.' => 'Ungültiger HEX-Farb-Code',
    'Invalid formatted value.' => 'Ungültiger formatierter Wert.',
    'Invalid guideline section ID.' => 'Ungültige Guideline-Sektions-ID.',
    'Invalid hotspot template ID.' => 'Ungültige Hotspot-Vorlagen-ID.',
    'Invalid login credentials.' => 'Ungültige Anmeldedaten.',
    'Invalid or expired token.' => 'Ungültiger oder abgelaufener Token.',
    'Invalid password.' => 'Ungültiges Passwort.',
    'Invalid primary comment ID.' => 'Ungültige primäre Kommentar-ID.',
    'Invalid project ID.' => 'Ungültige Projekt-ID.',
    'Invalid prototype ID.' => 'Ungültige Prototyp-ID.',
    'Invalid screen ID.' => 'Ungültige Screen-ID.',
    'Last name' => 'Nachname',
    'Left' => 'Links',
    'Message' => 'Nachricht',
    'New password' => 'Neues Passwort',
    'New password confirm' => 'Neues Passwort bestätigen',
    'Notify on each comment' => 'Bei jedem Kommentar benachrichtigen',
    'Notify on mention' => 'Bei Erwähnungen benachrichtigen',
    'Old password' => 'Bisheriges Passwort',
    'Oops, an error occurred while processing your request.' => 'Upps, es ist eine Fehler während der Bearbeitung deiner Anfrage aufgetreten.',
    'Order' => 'Reihenfolge',
    'Overlay position' => 'Overlay-Position',
    'Password' => 'Passwort',
    'Password confirm' => 'Passwort bestätigen',
    'Passwords don\'t match.' => 'Passwörter stimmen nicht überein.',
    'Prototypes' => 'Prototypen',
    'Reply to' => 'Antwort an',
    'Scale factor' => 'Skalierungsfaktor',
    'Screen' => 'Screen',
    'Status' => 'Status',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'Die Ressource die du suchst existiert nicht oder ist derzeit nicht verfügbar.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'Es existier bereits ein Projekt-Administrator mit dieser E-Mail-Adresse. Projekt-Administratoren sollten den Adminbereich nutzen, um Kommentare zu hinterlassen.',
    'Title' => 'Titel',
    'Token' => 'Token',
    'Top' => 'Oben',
    'Transition' => 'Übergang',
    'Type' => 'Typ',
    'Url' => 'URL',
    'User with such email address already exist.' => 'Es existiert bereits ein Nutzer mit dieser E-Mail Adresse.',
    'Vertical position' => 'Vertikale Position',
    'Width' => 'Breite',
    'You are not allowed to perform this request.' => 'Du bist nicht berechtigt diese Anfrage auszuführen.',
    'You cannot unlink the only user of the project.' => 'Du kannst den einzigen Nutzer dieses Projektes nicht entfernen.',
);
