<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Kontoaktivierung',
    'Activate account' => 'Konto aktivieren',
    'Administrator assignment' => 'Zuweisung als Administrator ',
    'Administrator discharge' => 'Zuweisung als Administrator entfernt',
    'Best Regards' => 'Viele Grüße',
    'Click on the button below for detail view and other options:' => 'Klicke den folgenden Button um die Detailansicht und weitere Optionen aufzurufen:',
    'Click on the button below to activate your account:' => 'Klicke auf den nachfolgenden Button um dein Konto zu aktivieren:',
    'Click on the button below to explore the project:' => 'Klicke auf den nachfolgenden Button um das Projekt zu durchsuchen:',
    'Confirm email address change' => 'Bestätige die Änderung deiner E-Mail Adresse',
    'Detail view' => 'Detailansicht',
    'Email change confirmation' => 'Bestätigung der Änderung der E-Mail Adresse',
    'Explore project' => 'Projekt durchsuchen',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Aus Sicherheitsgründen bitten wir dich, das generierte Passwort schnellstmöglich zu ändern.',
    'Hello' => 'Hallo',
    'Password reset request' => 'Anfrage zum Zurücksetzen des Passworts',
    'Presentator Team' => 'Presentator Team',
    'Reset password' => 'Passwort zurücksetzen',
    'Successfully authenticated' => 'Authentifizierung erfolgreich',
    'Thank you for your registration at Presentator.' => 'Danke für deine Registrierung bei Presentator',
    'To update your password, click the button below:' => 'Um dein Passwort zu aktualisieren, klicke auf den nachfolgenden Button:',
    'Unread comment' => 'Ungelesene Kommentare',
    'View design' => 'Design betrachten',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Wir haben ein zufälliges Passwort für dein Konto generiert, damit du dich ohne die Authentifizierung bei einem Dienst eines Drittanbieters anmelden kannst.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Wir haben eine Anfrage erhalten, die E-Mail Adresse deines Presentator-Kontos von {oldEmail} in {newEmail} zu ändern.',
    'We\'ve received a request to reset your account password.' => 'Wir haben eine Anfrage erhalten, dein Passwort zurückzusetzen.',
    'You are invited to review the design for project "{projectTitle}".' => 'Du wurdest eingeladen, dass Design des Projekts "{projectTitle}" zu überprüfen.',
    'You have been assigned as administrator to project "{projectTitle}".' => 'Du wurdest dem Projekt "{projectTitle}" als Administrator hinzugefügt.',
    'You have been mentioned in a comment' => 'Du wurdest in einem Kommentar erwähnt',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Du wurdest in einem Kommentar des Screens "{screenTitle}" des Projekts "{projectTitle}" erwähnt:',
    'You have been removed from project "{projectTitle}".' => 'Du wurdest vom Projekt "{projectTitle}" entfernt.',
    'You have unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Es gibt ungelesene Kommentare für den Screen "{screenTitle}" des Projekts "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Dein Presentator-Konto wurde erfolgreich erstellt.',
    '{projectTitle} preview' => '{projectTitle} Vorschau',
);
