<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Из соображений безопасности просим вас как можно скорее сменить сгенерированный пароль.',
    'Successfully authenticated' => 'Успешная авторизация',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'Мы создали случайный пароль для вашей учетной записи, чтобы иметь возможность входа в систему без необходимости сторонней (3rd party) аутентификации.',
    'A new comment was left for project "{projectTitle}".' => 'К проекту "{projectTitle}" был добавлен новый комментарий.',
    'Account activation' => 'Активация аккаунта',
    'Activate account' => 'Активировать аккаунт',
    'Administrator assignment' => 'Назначение администратора',
    'Administrator discharge' => 'Сброс администратора',
    'Best Regards' => 'С наилучшими пожеланиями',
    'Click on the button below for detail view and other options:' => 'Нажмите кнопку ниже для просмотра и других параметров:',
    'Click on the button below to activate your account:' => 'Нажмите на кнопку ниже, чтобы активировать свою учетную запись:',
    'Click on the button below to explore the project:' => 'Нажмите кнопку ниже, чтобы посмотреть проект:',
    'Click on the button below to reset it and set a new one:' => 'Нажмите на кнопку ниже, чтобы сбросить пароль:',
    'Confirm email address change' => 'Подтвердить смену E-mail',
    'Detail view' => 'Подробнее',
    'Email change request' => 'Запросить смену E-mail',
    'Explore project' => 'Перейти к проекту',
    'From' => 'От',
    'Hello' => 'Здравствуйте',
    'If you need any further help don\'t hesitate to contact us at {supportEmail}.' => 'Если вам нужна дополнительная помощь, не стесняйтесь обращаться к нам по адресу {supportEmail}.',
    'If you think that this message is a mistake or you need any further help, don\'t hesitate to contact us at {supportEmail}.' => 'Если вы считаете, что это сообщение является ошибкой или вам нужна дополнительная помощь, не стесняйтесь обращаться к нам в службу поддержки {supportEmail}.',
    'Message' => 'Сообщение',
    'New comment' => 'Новый комментарий',
    'P.S. If you don\'t want to receive any comments notifications, you could update your preferences at your Presentator account settings page.' => 'P.S. Если вы не хотите получать сообщения о комментариях, вы можете изменить настройки на странице управления вашим аккаунтом Presentator.',
    'Password reset request' => 'Запрос на смену пароля',
    'Presentator Team' => 'Команда Presentator',
    'Reset password' => 'Сброс пароля',
    'Screen' => 'Экран',
    'Thank you for registering to {appLink}.' => 'Спасибо на регистрацию в {appLink}.',
    'View project' => 'Смотреть проект',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'Мы получили запрос на смену E-mail вашего аккаунта c {oldEmail} на {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'Мы получили запрос на смену пароля вашего аккаунта.',
    'You are assigned as admin to project "{projectTitle}".' => 'Вы назначены администратором проекта "{projectTitle}".',
    'You are invited to review the design for "{projectTitle}".' => 'Вас пригласили оценить дизайн "{projectTitle}".',
    'You are no longer an administrator to project "{projectTitle}".' => 'Вы больше не администратор проекта "{projectTitle}".',
    'You have been mentioned in a comment' => 'Вас упомянули в комментарии',
    'You have been mentioned in a comment for project "{projectTitle}".' => 'Вас упомянули в комментарии к проекту "{projectTitle}".',
    '{projectTitle} preview' => 'Предварительный просмотр {projectTitle}',
);
