<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Alignment' => 'Uitlijning',
    'Allow comments' => 'Opmerkingen toestaan',
    'Allow guideline' => 'Guideline toestaan',
    'Archived' => 'Gearchiveerd',
    'Avatar' => 'Avatar',
    'Background' => 'Achtergrond',
    'Client' => 'Client',
    'Code' => 'Code',
    'Delete avatar' => 'Verwijder avatar',
    'Description' => 'Omschrijving',
    'Email' => 'E-mail',
    'Email address domain is not allowed.' => 'E-mail domein niet toegestaan',
    'Failed to authorize.' => 'Autorisatie gefaald',
    'File' => 'File',
    'First name' => 'Voornaam',
    'Fixed footer' => 'Vaste footer',
    'Fixed header' => 'Vaste header',
    'From' => 'Van',
    'Height' => 'Hoogte',
    'Horizontal position' => 'Horizontale positie',
    'Invalid HEX color code.' => 'Ongeldig HEX kleur code.',
    'Invalid formatted value.' => 'Ongeldig geformatteerde waarde.',
    'Invalid guideline section ID.' => 'Ongeldig guideline sectie ID.',
    'Invalid hotspot template ID.' => 'Ongeldig hotspot template ID.',
    'Invalid login credentials.' => 'Onjuiste inloggegevens.',
    'Invalid or expired token.' => 'Ongeldig of verlopen token.',
    'Invalid password.' => 'Ongeldig wachtwoord.',
    'Invalid primary comment ID.' => 'Ongeldig eerste reactie ID.',
    'Invalid project ID.' => 'Ongeldig project ID.',
    'Invalid prototype ID.' => 'Ongeldig prototype ID.',
    'Invalid screen ID.' => 'Ongeldig scherm ID.',
    'Last name' => 'Achternaam',
    'Left' => 'Links',
    'Message' => 'Bericht',
    'New password' => 'Nieuw wachtwoord',
    'New password confirm' => 'Bevestig nieuw wachtwoord',
    'Notify on each comment' => 'Melding bij elke opmerking',
    'Notify on mention' => 'Melding als je getagd bent',
    'Old password' => 'Oude wachtwoord',
    'Oops, an error occurred while processing your request.' => 'Oeps, er is iets fout gegaan bij het verwerken van je opdracht.',
    'Order' => 'Order',
    'Overlay position' => 'Overlay position',
    'Password' => 'Wachtwoord',
    'Password confirm' => 'Bevestig wachtwoord',
    'Passwords don\'t match.' => 'Wachtwoorden komen niet overeen.',
    'Prototypes' => 'Prototypen',
    'Reply to' => 'Antwoord aan',
    'Scale factor' => 'Scale factor',
    'Screen' => 'Scherm',
    'Status' => 'Status',
    'The resource you are looking for does not exist or is temporary unavailable.' => 'De bron die u zoekt, bestaat niet of is tijdelijk niet beschikbaar.',
    'There is a project admin with such email address. Project admins should use the admin area to comment.' => 'Er is een projecteigenaar met dit e-mailadres. Projecteigenaren moeten de beheerdersruimte gebruiken om feedback te geven.',
    'Title' => 'Titel',
    'Token' => 'Token',
    'Top' => 'Top',
    'Transition' => 'Overgang',
    'Type' => 'Type',
    'Url' => 'Url',
    'User with such email address already exist.' => 'Er bestaat al een gebruiker met dit e-mailadres.',
    'Vertical position' => 'Verticale positie',
    'Width' => 'Breedte',
    'You are not allowed to perform this request.' => 'You are not allowed to perform this request.',
    'You cannot unlink the only user of the project.' => 'Je kan niet de laatste gebruiker van een project halen.',
);
