<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Account activation' => 'Accountactivatie',
    'Activate account' => 'Activeer account',
    'Administrator assignment' => 'Projecteigenaar',
    'Administrator discharge' => 'Projecteigenaar af',
    'Best Regards' => 'Met vriendelijke groet',
    'Click on the button below for detail view and other options:' => 'Klik op de knop hieronder voor de details en andere opties:',
    'Click on the button below to activate your account:' => 'Klik op de knop hieronder om je account te activeren:',
    'Click on the button below to explore the project:' => 'Klik hieronder om het project te ontdekken:',
    'Confirm email address change' => 'Bevestig wijziging e-mailadres',
    'Detail view' => 'Detail-overzicht',
    'Email change confirmation' => 'Bevestiging wijziging e-mailadres',
    'Explore project' => 'Verken het project',
    'For security reasons, we encourage you to change the generated password as soon as possible.' => 'Om veiligheidsredenen, moedigen we je aan om het automatisch gegenereerde wachtwoord zo snel mogelijk aan te passen.',
    'Hello' => 'Hallo',
    'Password reset request' => 'Verzoek tot wachtwoordherstel',
    'Presentator Team' => 'Het Presentator-team',
    'Reset password' => 'Wachtwoord herstellen',
    'Successfully authenticated' => 'Met succes geauthenticeerd',
    'Thank you for your registration at Presentator.' => 'Dankjewel voor je registratie bij Presentator.',
    'To update your password, click the button below:' => 'Klik op de knop hieronder om je wachtwoord aan te passen:',
    'Unread comment' => 'Ongelezen opmerking',
    'View design' => 'Bekijk ontwerp',
    'We have generated a random password for your account in order to be able to login without the need of 3rd party authentication.' => 'We hebben een automatisch gegenereerd wachtwoord voor je aangemaakt, waarmee je kunt inloggen zonder authenticatie via een derde partij.',
    'We\'ve received a request to change your Presentator account email address from {oldEmail} to {newEmail}.' => 'We hebben een verzoek ontvangen om het e-mailadres van je Presentator-account te wijzigen van {oldEmail} naar {newEmail}.',
    'We\'ve received a request to reset your account password.' => 'We hebben een verzoek ontvangen om het wachtwoord van je account te herstellen.',
    'You are invited to review the design for project "{projectTitle}".' => 'Je ben uitgenodigd om feedback te geven op het ontwerp voor het project "{projectTitle}".',
    'You have been assigned as administrator to project "{projectTitle}".' => 'Je bent toegewezen als eigenaar van het project "{projectTitle}".',
    'You have been mentioned in a comment' => 'Je bent getagged in een opmerking',
    'You have been mentioned in a comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Je bent getagged in een opmerking bij het scherm "{screenTitle}" in het project "{projectTitle}":',
    'You have been removed from project "{projectTitle}".' => 'Je beent ontkoppeld van het project "{projectTitle}".',
    'You have an unread comment for screen "{screenTitle}" in project "{projectTitle}":' => 'Je hebt een ongelezen opmerking bij het scherm "{screenTitle}" in het project "{projectTitle}":',
    'Your Presentator account was successfully created.' => 'Je Presentator-account is met succes gecreëerd.',
    '{projectTitle} preview' => '{projectTitle} voorbeeld',
);
